// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RectangleSearchAPI.Data;

#nullable disable

namespace RectangleSearchAPI.Migrations
{
    [DbContext(typeof(SqlServerDbContext))]
    [Migration("20230529020135_[1] Initial Migration")]
    partial class _1InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RectangleSearchAPI.Models.Coordinate", b =>
                {
                    b.Property<Guid>("IdCoordinate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdRectangle")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("X")
                        .HasColumnType("float");

                    b.Property<double>("Y")
                        .HasColumnType("float");

                    b.HasKey("IdCoordinate");

                    b.HasIndex("IdRectangle");

                    b.ToTable("Coordinates");
                });

            modelBuilder.Entity("RectangleSearchAPI.Models.Rectangle", b =>
                {
                    b.Property<Guid>("IdRectangle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRectangle");

                    b.ToTable("Rectangles");
                });

            modelBuilder.Entity("RectangleSearchAPI.Models.Coordinate", b =>
                {
                    b.HasOne("RectangleSearchAPI.Models.Rectangle", "Rectangle")
                        .WithMany("Coordinates")
                        .HasForeignKey("IdRectangle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rectangle");
                });

            modelBuilder.Entity("RectangleSearchAPI.Models.Rectangle", b =>
                {
                    b.Navigation("Coordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
