// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RectangleSearchAPI.Data;

#nullable disable

namespace RectangleSearchAPI.Migrations
{
    [DbContext(typeof(RectangleSearchAPIDbContext))]
    [Migration("20230528090446_Change relations to with many")]
    partial class Changerelationstowithmany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RectangleSearchAPI.Models.CoordinateModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RectangleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("X")
                        .HasColumnType("float");

                    b.Property<double>("Y")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("RectangleId");

                    b.ToTable("Coordinates");
                });

            modelBuilder.Entity("RectangleSearchAPI.Models.RectangleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BottomRightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TopLeftId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BottomRightId");

                    b.HasIndex("TopLeftId");

                    b.ToTable("Rectangles");
                });

            modelBuilder.Entity("RectangleSearchAPI.Models.CoordinateModel", b =>
                {
                    b.HasOne("RectangleSearchAPI.Models.RectangleModel", "Rectangle")
                        .WithMany()
                        .HasForeignKey("RectangleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rectangle");
                });

            modelBuilder.Entity("RectangleSearchAPI.Models.RectangleModel", b =>
                {
                    b.HasOne("RectangleSearchAPI.Models.CoordinateModel", "BottomRightCoordinate")
                        .WithMany()
                        .HasForeignKey("BottomRightId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RectangleSearchAPI.Models.CoordinateModel", "TopLeftCoordinate")
                        .WithMany()
                        .HasForeignKey("TopLeftId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BottomRightCoordinate");

                    b.Navigation("TopLeftCoordinate");
                });
#pragma warning restore 612, 618
        }
    }
}
